import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const scenarios = JSON.parse(await readFile(new URL("../lib/scenarios.json", import.meta.url), "utf8"));
const categories = ["delivery","bank-payment","subscriptions","tech-support","school-kids","account-lockout"];
const layouts = ["cta-hero","security-banner","receipt-table","tracking-card"];
const brands = ["swiftbox","riverline","streamly","softshield","maple-district","paynest"];
const realBrands = /\b(?:Apple|Amazon|IRS|FedEx|Microsoft|Chase|Citibank|Wells Fargo|Bank of America)\b/i;
const lureChrome = /\b(?:fictional|practice|drill|coaching)\b/i;
test("scenario pack covers every requested category, layout, and fictional brand", () => { assert.ok(scenarios.length >= 6); for (const value of categories) assert.ok(scenarios.some(s=>s.category===value), value); for (const value of layouts) assert.ok(scenarios.some(s=>s.layoutId===value), value); for (const value of brands) assert.ok(scenarios.some(s=>s.brandId===value), value); });
test("scenarios have unique complete safe lure fields", () => { assert.equal(new Set(scenarios.map(s=>s.id)).size,scenarios.length); for (const s of scenarios) { for (const field of ["id","category","layoutId","brandId","fromName","subject","preview","ctaLabel"]) assert.ok(s[field]?.trim(),`${s.id}: ${field}`); const lure=[s.fromName,s.subject,s.preview,s.preheader,...s.bodyParagraphs,s.ctaLabel,...s.footerLines].join(" "); assert.doesNotMatch(lure,realBrands,s.id); assert.doesNotMatch(lure,lureChrome,s.id); assert.equal(s.lesson.length,3); } });
test("only the two approved invented portals opt in",()=>{ assert.deepEqual(new Set(scenarios.filter(s=>s.portalStage).map(s=>s.brandId)),new Set(["maple-district","paynest"])); });
