import { integer, pgEnum, pgTable, primaryKey, text, timestamp, unique } from "drizzle-orm/pg-core";

export const agreementStatus = pgEnum("AgreementStatus", ["draft", "active"]);
export const drillEventType = pgEnum("DrillEventType", ["drill.sent", "drill.revealed", "lure.engaged", "drill.failed"]);
export const organizers = pgTable("Organizer", { id: text("id").primaryKey().$defaultFn(crypto.randomUUID), name: text("name"), email: text("email").unique(), emailVerified: timestamp("emailVerified", { mode: "date" }), image: text("image") });
export const accounts = pgTable("Account", { userId: text("userId").notNull().references(() => organizers.id, { onDelete: "cascade" }), type: text("type").notNull(), provider: text("provider").notNull(), providerAccountId: text("providerAccountId").notNull(), refresh_token: text("refresh_token"), access_token: text("access_token"), expires_at: integer("expires_at"), token_type: text("token_type"), scope: text("scope"), id_token: text("id_token"), session_state: text("session_state") }, (table) => [primaryKey({ columns: [table.provider, table.providerAccountId] })]);
export const sessions = pgTable("Session", { sessionToken: text("sessionToken").primaryKey(), userId: text("userId").notNull().references(() => organizers.id, { onDelete: "cascade" }), expires: timestamp("expires", { mode: "date" }).notNull() });
export const verificationTokens = pgTable("VerificationToken", { identifier: text("identifier").notNull(), token: text("token").notNull(), expires: timestamp("expires", { mode: "date" }).notNull() }, (table) => [primaryKey({ columns: [table.identifier, table.token] })]);
export const householdAgreements = pgTable("HouseholdAgreement", { id: text("id").primaryKey().$defaultFn(crypto.randomUUID), organizerId: text("organizerId").notNull().references(() => organizers.id, { onDelete: "cascade" }).unique(), termsVersion: text("termsVersion").notNull(), status: agreementStatus("status").notNull().default("draft"), activatedAt: timestamp("activatedAt", { mode: "date" }) });
export const members = pgTable("Member", { id: text("id").primaryKey().$defaultFn(crypto.randomUUID), name: text("name").notNull(), email: text("email").notNull(), householdId: text("householdId").notNull().references(() => householdAgreements.id, { onDelete: "cascade" }) });
export const attempts = pgTable("Attempt", { id: text("id").primaryKey().$defaultFn(crypto.randomUUID), memberId: text("memberId").notNull().references(() => members.id, { onDelete: "cascade" }), scenarioId: text("scenarioId").notNull(), drillToken: text("drillToken").notNull().unique().$defaultFn(crypto.randomUUID), createdAt: timestamp("createdAt", { mode: "date" }).notNull().defaultNow(), scheduledFor: timestamp("scheduledFor", { mode: "date" }) });
export const drillEvents = pgTable("DrillEvent", { id: text("id").primaryKey().$defaultFn(crypto.randomUUID), attemptId: text("attemptId").notNull().references(() => attempts.id, { onDelete: "cascade" }), type: drillEventType("type").notNull(), occurredAt: timestamp("occurredAt", { mode: "date" }).notNull().defaultNow(), summary: text("summary").notNull() }, (table) => [unique().on(table.attemptId, table.type)]);
export const botInstalls = pgTable("BotInstall", { id: text("id").primaryKey().$defaultFn(crypto.randomUUID), householdId: text("householdId").notNull().references(() => householdAgreements.id, { onDelete: "cascade" }).unique(), token: text("token").notNull().unique(), active: integer("active").notNull().default(1), householdPaused: integer("householdPaused").notNull().default(0) });
