import { and, eq, getTableColumns, sql } from "drizzle-orm";
import scenariosData from "./scenarios.json";
import { db } from "./db";
import { attempts, drillEvents, householdAgreements, members, organizers } from "./schema";
import type { Attempt, HouseholdAgreement, Scenario } from "./types";

export const scenarios = scenariosData as Scenario[];
const agreement = (row: typeof householdAgreements.$inferSelect & { organizerName: string | null }): HouseholdAgreement => ({ id: row.id, organizerName: row.organizerName ?? "Organizer", termsVersion: row.termsVersion, status: row.status, activatedAt: row.activatedAt?.toISOString() });
const attempt = (row: typeof attempts.$inferSelect): Attempt => ({ ...row, createdAt: row.createdAt.toISOString() });

export async function getHousehold(organizerId: string) { const [row] = await db.select({ ...getTableColumns(householdAgreements), organizerName: organizers.name }).from(householdAgreements).innerJoin(organizers, eq(householdAgreements.organizerId, organizers.id)).where(eq(householdAgreements.organizerId, organizerId)); return row ? agreement(row) : undefined; }
export async function activateHousehold(organizerId: string) { await db.update(householdAgreements).set({ status: "active", activatedAt: new Date() }).where(eq(householdAgreements.organizerId, organizerId)); return getHousehold(organizerId); }
export async function getMembers(organizerId: string) { return db.select({ id: members.id, name: members.name, email: members.email, householdId: members.householdId }).from(members).innerJoin(householdAgreements, and(eq(members.householdId, householdAgreements.id), eq(householdAgreements.organizerId, organizerId))).orderBy(members.name); }
export async function addMember(organizerId: string, name: string, email: string) { const cleanName = name.trim(), cleanEmail = email.trim(); if (!cleanName || !cleanEmail) return; const [household] = await db.select({ id: householdAgreements.id }).from(householdAgreements).where(eq(householdAgreements.organizerId, organizerId)); if (!household) return; const [created] = await db.insert(members).values({ name: cleanName, email: cleanEmail, householdId: household.id }).returning(); return created; }
export async function findAttempt(token: string) { const [row] = await db.select().from(attempts).where(eq(attempts.drillToken, token)); return row ? attempt(row) : undefined; }
export async function sendAttempt(organizerId: string, memberId: string, scenarioId: string) { const [found] = await db.select({ member: members, status: householdAgreements.status }).from(members).innerJoin(householdAgreements, and(eq(members.householdId, householdAgreements.id), eq(householdAgreements.organizerId, organizerId))).where(eq(members.id, memberId)); const scenario = scenarios.find((item) => item.id === scenarioId); if (!found || found.status !== "active" || !scenario) return; const [created] = await db.insert(attempts).values({ memberId, scenarioId }).returning(); return { member: found.member, scenario, attempt: attempt(created) }; }
export async function recordLureOpened(token: string) { const found = await findAttempt(token); if (!found) return; await db.insert(drillEvents).values({ attemptId: found.id, type: "lure_opened" }).onConflictDoNothing(); return found; }
export async function getReport(organizerId: string, memberId: string) { const [row] = await db.select({ sent: sql<number>`count(distinct ${attempts.id})::int`, lureEngagements: sql<number>`count(distinct ${drillEvents.id})::int` }).from(members).innerJoin(householdAgreements, and(eq(members.householdId, householdAgreements.id), eq(householdAgreements.organizerId, organizerId))).leftJoin(attempts, eq(attempts.memberId, members.id)).leftJoin(drillEvents, and(eq(drillEvents.attemptId, attempts.id), eq(drillEvents.type, "lure_opened"))).where(eq(members.id, memberId)); return row ?? { sent: 0, lureEngagements: 0 }; }
